### PR TITLE
Increase postal code length to avoid truncation

### PR DESCRIPTION
**Pull request by Zosoled**
# Critical Changes
* Household: Increase MailingPostalCode__c to 20 digits, up from 10.
  * This matches the field length of standard postal code fields [(source)](https://powerofus.force.com/s/feed/0D58000001maPqf).

# Changes
* package.xml: Remove duplicated CustomLabel metadata type.

# Issues Closed
SalesforceFoundation/Cumulus#1266

### CODE REVIEW

**Comment by Zosoled** [comment]
Only two references to this field that I could find:

1. Formula_MailingAddress__c: Household formula field, still compiles OK.
  * This is further used in Contact.Formula_HouseholdMailingAddress__c, which also compiles OK.
2. ManageHouseholdjs: Static resource, couldn't find where this resource is actually used.

**Comment by judisohn** [comment]
Thanks for the contribution once again @Zosoled!

**Comment by judisohn** [comment]
**lurch: add

**Comment by Zosoled** [comment]
Cancelling and resubmitting due to age and contact info changes.

**Comment by Zosoled** [comment]
Closed due to unresponsiveness.

**Pull request closed without merging**
